### ISSUE TITLE
ILQL crashes with AttributeError: 'ILQLConfig' object has no attribute 'chunk_size'

### ISSUE THREAD

**Issue by ntoxeg** [CarperAI/trlx#205]
### 🐛 Describe the bug

I ran a script with a configuration file based on the example `ilql_config.yml`. I got the following error:
```
Traceback (most recent call last):
  File "/home/ubuntu/rlhf/rl_tuning/tune.py", line 86, in <module>
    tuned_model = trlx.train(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/rlhf-fxRBPSH--py3.10/lib/python3.10/site-packages/trlx/trlx.py", line 79, in train
    trainer, pipeline, chunk_size=config.method.chunk_size
AttributeError: 'ILQLConfig' object has no attribute ‘chunk_size'
```
With the following extended traceback:
```
/home/ubuntu/.cache/pypoetry/virtualenvs/rlhf-fxRBPSH--py3.10/lib/python3.10/site-packages/trlx/ │
│ trlx.py:79 in train                                                                              │
│                                                                                                  │
│    76 │   │   │   prompts, max_prompt_length, trainer.tokenizer                                  │
│    77 │   │   )                                                                                  │
│    78 │   │   orch = get_orchestrator(config.train.orchestrator)(                                │
│ ❱  79 │   │   │   trainer, pipeline, chunk_size=config.method.chunk_size                         │
│    80 │   │   )                                                                                  │
│    81 │   │   orch.make_experience(config.method.num_rollouts)                                   │
│    82                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'ILQLConfig' object has no attribute ‘chunk_size'
```

The configuration file definitely has the following:
```
  pipeline: "PromptPipeline"
  orchestrator: "OfflineOrchestrator"
  trainer: “AccelerateILQLTrainer"
```

And there is no `chunk_size` in the `method` section (as it’s just directly copied from your `ilql_config.yml`).

### Which trlX version are you using?

git:84a07113d8ced1497c5a7941a02f9c534bb4e185

### Additional system and package information

Ubuntu focal, Python 3.10, transformers==4.25.1

**Comment by jon-tow** [comment]
Hi @ntoxeg ! What is your call to `trlx.train`? L79 points to the `PPO` block - make sure to not pass in a `reward_fn` when running ILQL.

**Comment by ntoxeg** [comment]
@jon-tow I see, that was the mistake.
