### ISSUE TITLE
ILQL bfloat16

### ISSUE THREAD

**Issue by maxreciprocate** [CarperAI/trlx#243]
### 🐛 Describe the bug

```
Traceback (most recent call last):
  File "examples/randomwalks/ilql_randomwalks.py", line 34, in <module>
    main()
  File "examples/randomwalks/ilql_randomwalks.py", line 23, in main
    trlx.train(
  File "/trlx/trlx/trlx.py", line 127, in train
    trainer.learn()
  File "/trlx/trlx/trainer/accelerate_base_trainer.py", line 468, in learn
    results = self.evaluate()
  File "/trlx/trlx/trainer/accelerate_base_trainer.py", line 323, in evaluate
    samples = self.generate_eval(
  File "/trlx/trlx/trainer/accelerate_base_trainer.py", line 273, in generate_eval
    return self.accelerator.unwrap_model(self.model).generate(
  File "/trlx/trlx/trainer/nn/ilql_models.py", line 312, in generate
    out = self.forward(
  File "/trlx/trlx/trainer/nn/ilql_models.py", line 272, in forward
    qs, target_qs, vs = self.ilql_heads(
  File "/trlx/.env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/trlx/trlx/trainer/nn/ilql_models.py", line 173, in forward
    qs = tuple(q_head(actions_hs) for q_head in self.q_heads)
  File "/trlx/trlx/trainer/nn/ilql_models.py", line 173, in <genexpr>
    qs = tuple(q_head(actions_hs) for q_head in self.q_heads)
  File "/trlx/.env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/trlx/.env/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/trlx/.env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/trlx/.env/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasLtMatmul( ltHandle, computeDesc.descriptor(), &alpha_val, mat1_ptr, Adesc.descriptor(), mat2_ptr, Bdesc.descriptor(), &beta_val, result_ptr, Cdesc.descriptor(),
result_ptr, Cdesc.descriptor(), &heuristicResult.algo, workspace.data_ptr(), workspaceSize, at::cuda::getCurrentCUDAStream())
```
```
compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: false
fsdp_config: {}
main_process_port: 1234
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
use_cpu: false
```
`accelerate launch --num_processes 2 --config_file bf16-zero2-deepspeed.yaml examples/randomwalks/ilql_randomwalks.py`

### Which trlX version are you using?

[main](https://github.com/CarperAI/trlx/tree/2855d0ce3aca741f6fa9e7bc41d4cc14a0b83ee1)

### Additional system and package information

```torch==1.13.0+cu116 deepspeed==0.8.0 CUDA Version: 11.6```

**Comment by jon-tow** [comment]
(Note: I'm not able to reproduce this from `torch==1.13.0+cu117 CUDA Version: 11.7 deepspeed==0.8.0`)
