### ISSUE TITLE
[bug] Support for Soft Prompts in PPO Model

### ISSUE THREAD

**Issue by daia99** [CarperAI/trlx#29]
Towards replication of ELM Stage 3, I'm looking into adding softprompts to train a conditional learnable embedding with PPO for each terrain mentioned in the paper.

Following https://github.com/kipgparker/soft-prompt-tuning.

Outlined code snippet example, and tracebacks for varying number of softprompt tokens. Will come back to this, but let me know if you have any suggestions for modifying the orchestrator.

Using the ppo_sentiments example and soft prompt implementation:
```python
if __name__ == "__main__":
    cfg = TRLConfig.load_yaml("configs/ppo_config.yml")

    sentiment_pipe = pipeline(
        "sentiment-analysis", "lvwerra/distilbert-imdb", device=-1
    )

    def reward_fn(samples: List[str]):
        sent_kwargs = {
            "return_all_scores": True,
            "function_to_apply": None,
            "batch_size": cfg.method.chunk_size,
        }
        pipe_outputs = sentiment_pipe(samples, **sent_kwargs)
        scores = torch.tensor([output[1]["score"] for output in pipe_outputs])
        return scores

    model: AcceleratePPOModel = get_model(cfg.model.model_type)(cfg)

    # setup soft prompt embeddings with 'n' prefix tokens, init from model vocab
    n_tokens = 1
    initialize_from_vocab = True
    
    s_wte = SoftEmbedding(model.model.gpt.get_input_embeddings(), 
                      n_tokens=n_tokens, 
                      initialize_from_vocab=initialize_from_vocab)

    model.model.gpt.set_input_embeddings(s_wte)
    
    pipeline: PPOPipeline = get_pipeline(cfg.train.pipeline)(model.tokenizer, cfg)
    orch: PPOOrchestrator = get_orchestrator(cfg.train.orchestrator)(
        model, pipeline, reward_fn=reward_fn, chunk_size=cfg.method.chunk_size
    )
    orch.make_experience(cfg.method.num_rollouts)
    model.learn()

    print("DONE!")
```

When `n_tokens = 1`, the following error occurs:
```
Traceback (most recent call last):
  File "/home/aleph/adai/trlx/examples/ppo_sentiments.py", line 101, in <module>
    orch.make_experience(cfg.method.num_rollouts)
  File "/home/aleph/adai/trlx/trlx/orchestrator/ppo_orchestrator.py", line 69, in make_experience
    logits, _, v = self.rl_model.model(all_tokens)
ValueError: not enough values to unpack (expected 3, got 2)
```

For `n_tokens = 20`:
```
Traceback (most recent call last):
  File "/home/aleph/adai/trlx/examples/ppo_sentiments.py", line 101, in <module>
    orch.make_experience(cfg.method.num_rollouts)
  File "/home/aleph/adai/trlx/trlx/orchestrator/ppo_orchestrator.py", line 62, in make_experience
    query_tensors, response_tensors, response_text = self.rl_model.act(batch)
  File "/home/aleph/adai/trlx/trlx/model/accelerate_base_model.py", line 104, in act
    _ = self.model(
  File "/home/aleph/anaconda3/envs/trlx/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aleph/adai/trlx/trlx/model/nn/ppo_models.py", line 76, in forward
    transformer_outputs = self.gpt.transformer(
  File "/home/aleph/anaconda3/envs/trlx/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aleph/anaconda3/envs/trlx/lib/python3.8/site-packages/transformers-4.22.2-py3.8.egg/transformers/models/gpt2/modeling_gpt2.py", line 851, in forward
    hidden_states = inputs_embeds + position_embeds
RuntimeError: The size of tensor a (20) must match the size of tensor b (4) at non-singleton dimension 1
```

**Comment by LouisCastricato** [comment]
Closed since this is a feature that is not necessary in core TRLX. If anyone needs this, it is available on our ELM repository. https://github.com/CarperAI/ELM
