### ISSUE TITLE
Reward model summarize do not return loss

### ISSUE THREAD

**Issue by joytianya** [CarperAI/trlx#309]
### 🐛 Describe the bug

When using [reward_model](https://github.com/CarperAI/trlx/tree/main/examples/summarize_rlhf/reward_model)The following error occurred,  What is the problem?

There was no problem with the previous training. This error occurred at 1001 steps

```python
[2023-02-15 20:27:00,404] [INFO] [torch_checkpoint_engine.py:27:commit] [Torch] Checkpoint global_step4000 is ready now!                                                                   
  2%|▏         | 1001/55545 [28:43<132:29:56,  8.75s/it]Traceback (most recent call last):                                                                                                 
  File "train_reward_model_t5.py", line 158, in <module>                                                                                                                                   
    Trainer(                                                                                                                                                                               
  File "/home/envs/yuan-rlhf/lib/python3.8/site-packages/transformers/trainer.py", line 1543, in train                                                                  
    return inner_training_loop(                                                                                                                                                            
  File "/home/envs/yuan-rlhf/lib/python3.8/site-packages/transformers/trainer.py", line 1791, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/envs/yuan-rlhf/lib/python3.8/site-packages/transformers/trainer.py", line 2539, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/envs/yuan-rlhf/lib/python3.8/site-packages/transformers/trainer.py", line 2584, in compute_loss
    raise ValueError(
ValueError: The model did not return a loss from the inputs, only the following keys: chosen_end_scores. For reference, the inputs it received are input_ids,attention_mask,labels.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/modelfun/zxw/env/trlx/examples/summarize_rlhf/reward_model/train_rewar │
│ d_model_t5.py:158 in <module>                                                │
│                                                                              │
│   155 │   # Create the collator to gather batches of pairwise comparisons    │
│   156 │   data_collator = DataCollatorReward()                               │
│   157 │                                                                      │
│ ❱ 158 │   Trainer(                                                           │
│   159 │   │   model=model,                                                   │
│   160 │   │   args=training_args,                                            │
│   161 │   │   train_dataset=train_dataset,                                   │
│                                                                              │
│ /home/modelfun/anaconda3/envs/yuan-rlhf/lib/python3.8/site-packages/transfor │
│ mers/trainer.py:1543 in train                                                │
│                                                                              │
│   1540 │   │   inner_training_loop = find_executable_batch_size(             │
│   1541 │   │   │   self._inner_training_loop, self._train_batch_size, args.a │
│   1542 │   │   )                                                             │
│ ❱ 1543 │   │   return inner_training_loop(                                   │
│   1544 │   │   │   args=args,                                                │
│   1545 │   │   │   resume_from_checkpoint=resume_from_checkpoint,            │
│   1546 │   │   │   trial=trial,                                              │
│                                                                              │
│ /home/modelfun/anaconda3/envs/yuan-rlhf/lib/python3.8/site-packages/transfor │
│ mers/trainer.py:1791 in _inner_training_loop                                 │
│                                                                              │
│   1788 │   │   │   │   │   with model.no_sync():                             │
│   1789 │   │   │   │   │   │   tr_loss_step = self.training_step(model, inpu │
│   1790 │   │   │   │   else:                                                 │
│ ❱ 1791 │   │   │   │   │   tr_loss_step = self.training_step(model, inputs)  │
│   1792 │   │   │   │                                                         │
│   1793 │   │   │   │   if (                                                  │
│   1794 │   │   │   │   │   args.logging_nan_inf_filter                       │
│                                                                              │
│ /home/modelfun/anaconda3/envs/yuan-rlhf/lib/python3.8/site-packages/transfor │
│ mers/trainer.py:2539 in training_step                                        │
│                                                                              │
│   2536 │   │   │   return loss_mb.reduce_mean().detach().to(self.args.device │
│   2537 │   │                                                                 │
│   2538 │   │   with self.compute_loss_context_manager():                     │
│ ❱ 2539 │   │   │   loss = self.compute_loss(model, inputs)                   │
│   2540 │   │                                                                 │
│   2541 │   │   if self.args.n_gpu > 1:                                       │
│   2542 │   │   │   loss = loss.mean()  # mean() to average on multi-gpu para │
│                                                                              │
│ /home/modelfun/anaconda3/envs/yuan-rlhf/lib/python3.8/site-packages/transfor │
│ mers/trainer.py:2584 in compute_loss                                         │
│                                                                              │
│   2581 │   │   │   │   loss = self.label_smoother(outputs, labels)           │
│   2582 │   │   else:                                                         │
│   2583 │   │   │   if isinstance(outputs, dict) and "loss" not in outputs:   │
│ ❱ 2584 │   │   │   │   raise ValueError(                                     │
│   2585 │   │   │   │   │   "The model did not return a loss from the inputs, │
│   2586 │   │   │   │   │   f"{','.join(outputs.keys())}. For reference, the  │
│   2587 │   │   │   │   )                                                     │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: The model did not return a loss from the inputs, only the following 
keys: chosen_end_scores. For reference, the inputs it received are 
input_ids,attention_mask,labels.
```

### Which trlX version are you using?

pip install with github

### Additional system and package information

python3.8

**Comment by PhungVanDuy** [comment]
Are you sure that you import the reward model correctly? Seem you make some modifications, can you please provide the code that you changed?

**Comment by joytianya** [comment]
Sorry, I changed to the ENCODER-DECODER model. Do you plan to make a DEMO code for the Encoder-DECODER model?

**Comment by PhungVanDuy** [comment]
> Sorry, I changed to the ENCODER-DECODER model. Do you plan to make a DEMO code for the Encoder-DECODER model?

We have an example with T5 [here](https://github.com/CarperAI/trlx/tree/main/examples/summarize_daily_cnn).

**Comment by joytianya** [comment]
Do you plan to make a Demo Reward code of the Encoder-DECODER model?

**Comment by PhungVanDuy** [comment]
> Do you plan to make a Demo Reward code of the Encoder-DECODER model?

We still do not have a plan for it yet, PR is welcome @joytianya .

**Comment by joytianya** [comment]
thank you ~
