### ISSUE TITLE
train trlx_gptj_text_summarization.py  post_summary_dict key error

### ISSUE THREAD

**Issue by jack-Dong** [CarperAI/trlx#340]
### 🐛 Describe the bug

```
[losses/total_loss: 0.34 | losses/policy_loss: 0.31 | losses/value_loss: 0.14]:   4%|████▍                                                                                                         | 256/6400 [14:08<1:23:11,  1.23it/s][RANK 0] Collecting rollouts
[rollout 16 / 128]:  12%|█████████████████████▊                                                                                                                                                        | 16/128 [00:10<01:12,  1.54it/s]Traceback (most recent call last):
  File "trlx_gptj_text_summarization.py", line 123, in <module>
    trainer = trlx.train(
  File "/cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/trlx/trlx.py", line 117, in train
    trainer.learn()
  File "/cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/trlx/trainer/accelerate_base_trainer.py", line 541, in learn
    self.post_epoch_callback()
  File "/cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/trlx/trainer/accelerate_ppo_trainer.py", line 227, in post_epoch_callback
    self.make_experience(self.config.method.num_rollouts, self.iter_count)
  File "/cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/trlx/trainer/accelerate_ppo_trainer.py", line 311, in make_experience
    self.reward_fn(
  File "trlx_gptj_text_summarization.py", line 87, in reward_fn
    original_samples = [text + post_summary_dict[text.strip()] for text in original_samples]
  File "trlx_gptj_text_summarization.py", line 87, in <listcomp>
    original_samples = [text + post_summary_dict[text.strip()] for text in original_samples]
KeyError: 'SUBREDDIT: r/personalfinance\nTITLE: Collections Account\nPOST: I\'ve seen the other posts about this, and appreciated the advice/looked into following some of it.  But now I\'d like some specific thoughts re: my situation.  Thanks in advance.\n\nSo, on my credit report is 2-year-old collections account from this company:    It was "last reported" in July of 2012.\n\nThe collections agency looks shady at best, and though they\'re "Bay Area" (which is where I live) their contact mailing address is in Georgia.  Weird, right?\n\nI believe the debt is from an emergency room visit I had a few years ago but I wouldn\'t know:  though I gave the hospital my name, phone, address, etc they never contacted me or sent me a bill and neither has the collections agency.  I thought that I was told I qualified for a low-income fee waiver but I was suffering from a concussion at the time so who knows.  \n\nAnyway, should I send a letter like this:???  Frankly this site looks less than legit, also, and since I honestly don\'t know my rights I don\'t want to be too aggressive/quote laws that aren\'t real.  Should I send it to the bogus Georgia address of this collections agency?  \n\nI\'m happy to pay this off to get rid of it but have no info on it, not even the amount.  And I\'d call them but I have no info and would prefer to get some documentation so I\'m not flying blind.\nTL;DR:'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/examples/summarize_rlhf/trlx_gptj_text_summari │
│ zation.py:123 in <module>                                                                        │
│                                                                                                  │
│   120 │   for i in range(len(val_prompts)):                                                      │
│   121 │   │   post_summary_dict[val_prompts[i]] = val_summaries[i]                               │
│   122 │                                                                                          │
│ ❱ 123 │   trainer = trlx.train(                                                                  │
│   124 │   │   reward_fn=reward_fn,                                                               │
│   125 │   │   prompts=train_prompts,                                                             │
│   126 │   │   eval_prompts=val_prompts[0:1000],  # sampling 1000 validation prompts for evalua   │
│                                                                                                  │
│ /cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/trlx/trlx.py:117 in train                      │
│                                                                                                  │
│   114 │   eval_pipeline = get_pipeline(config.train.pipeline)(eval_prompts, max_prompt_length,   │
│   115 │   trainer.add_eval_pipeline(eval_pipeline)                                               │
│   116 │                                                                                          │
│ ❱ 117 │   trainer.learn()                                                                        │
│   118 │   return trainer                                                                         │
│   119                                                                                            │
│                                                                                                  │
│ /cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/trlx/trainer/accelerate_base_trainer.py:541 in │
│ learn                                                                                            │
│                                                                                                  │
│   538 │   │   │   │                                                                              │
│   539 │   │   │   │   self.post_backward_callback()                                              │
│   540 │   │   │                                                                                  │
│ ❱ 541 │   ��   │   self.post_epoch_callback()                                                     │
│   542 │   │   tbar.close()                                                                       │
│   543 │                                                                                          │
│   544 │   @abstractmethod                                                                        │
│                                                                                                  │
│ /cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/trlx/trainer/accelerate_ppo_trainer.py:227 in  │
│ post_epoch_callback                                                                              │
│                                                                                                  │
│   224 │   │   │   self.store.export_history(location=self.rollout_logging_dir)                   │
│   225 │   │   self.store.clear_history()                                                         │
│   226 │   │   # Collect more rollouts for training                                               │
│ ❱ 227 │   │   self.make_experience(self.config.method.num_rollouts, self.iter_count)             │
│   228 │                                                                                          │
│   229 │   def post_backward_callback(self):                                                      │
│   230 │   │   self.kl_ctl.update(self.approx_kl, n_steps=self.config.train.batch_size)           │
│                                                                                                  │
│ /cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/trlx/trainer/accelerate_ppo_trainer.py:311 in  │
│ make_experience                                                                                  │
│                                                                                                  │
│   308 │   │   │   │                                                                              │
│   309 │   │   │   │   exp_score_time = time()                                                    │
│   310 │   │   │   │   all_scores = torch.tensor(                                                 │
│ ❱ 311 │   │   │   │   │   self.reward_fn(                                                        │
│   312 │   │   │   │   │   │   samples=all_str_samples,                                           │
│   313 │   │   │   │   │   │   prompts=all_str_prompts,                                           │
│   314 │   │   │   │   │   │   outputs=all_str_outputs,                                           │
│                                                                                                  │
│ /cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/examples/summarize_rlhf/trlx_gptj_text_summari │
│ zation.py:87 in reward_fn                                                                        │
│                                                                                                  │
│    84 │                                                                                          │
│    85 │   def reward_fn(samples: List[str], **kwargs):                                           │
│    86 │   │   original_samples = [text.split("TL;DR:")[0] + "TL;DR: " for text in samples]       │
│ ❱  87 │   │   original_samples = [text + post_summary_dict[text.strip()] for text in original_   │
│    88 │   │   original_scores = get_scores(original_samples)                                     │
│    89 │   │   scores = get_scores(samples)                                                       │
│    90 │   │   norms_scores = scores - original_scores                                            │
│                                                                                                  │
│ /cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/examples/summarize_rlhf/trlx_gptj_text_summari │
│ zation.py:87 in <listcomp>                                                                       │
│                                                                                                  │
│    84 │                                                                                          │
│    85 │   def reward_fn(samples: List[str], **kwargs):                                           │
│    86 │   │   original_samples = [text.split("TL;DR:")[0] + "TL;DR: " for text in samples]       │
│ ❱  87 │   │   original_samples = [text + post_summary_dict[text.strip()] for text in original_   │
│    88 │   │   original_scores = get_scores(original_samples)                                     │
│    89 │   │   scores = get_scores(samples)                                                       │
│    90 │   │   norms_scores = scores - original_scores                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'SUBREDDIT: r/personalfinance\nTITLE: Collections Account\nPOST: I\'ve seen the other posts about this, and appreciated the advice/looked into following some of it.  But now I\'d like some specific thoughts re: my 
situation.  Thanks in advance.\n\nSo, on my credit report is 2-year-old collections account from this company:    It was "last reported" in July of 2012.\n\nThe collections agency looks shady at best, and though they\'re "Bay Area" 
(which is where I live) their contact mailing address is in Georgia.  Weird, right?\n\nI believe the debt is from an emergency room visit I had a few years ago but I wouldn\'t know:  though I gave the hospital my name, phone, 
address, etc they never contacted me or sent me a bill and neither has the collections agency.  I thought that I was told I qualified for a low-income fee waiver but I was suffering from a concussion at the time so who knows.  
\n\nAnyway, should I send a letter like this:???  Frankly this site looks less than legit, also, and since I honestly don\'t know my rights I don\'t want to be too aggressive/quote laws that aren\'t real.  Should I send it to the 
bogus Georgia address of this collections agency?  \n\nI\'m happy to pay this off to get rid of it but have no info on it, not even the amount.  And I\'d call them but I have no info and would prefer to get some documentation so 
I\'m not flying blind.\nTL;DR:'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
```

the right key in post_summary_dict is:
```
'SUBREDDIT: r/personalfinance\nTITLE: Collections Account\nPOST: I\'ve seen the other posts about this, and appreciated the advice/looked into following some of it.  But now I\'d like some specific thoughts re: my situation.  Thanks in advance.\n\nSo, on my credit report is 2-year-old collections account from this company:    It was "last reported" in July of 2012.\n\nThe collections agency looks shady at best, and though they\'re "Bay Area" (which is where I live) their contact mailing address is in Georgia.  Weird, right?\n\nI believe the debt is from an emergency room visit I had a few years ago but I wouldn\'t know:  though I gave the hospital my name, phone, address, etc they never contacted me or sent me a bill and neither has the collections agency.  I thought that I was told I qualified for a low-income fee waiver but I was suffering from a concussion at the time so who knows.  \n\nAnyway, should I send a letter like this: ???  Frankly this site looks less than legit, also, and since I honestly don\'t know my rights I don\'t want to be too aggressive/quote laws that aren\'t real.  Should I send it to the bogus Georgia address of this collections agency?  \n\nI\'m happy to pay this off to get rid of it but have no info on it, not even the amount.  And I\'d call them but I have no info and would prefer to get some documentation so I\'m not flying blind.\nTL;DR:'
```
which has a space key before "???" as"should I send a letter like this: ???  Frankly".

### Which trlX version are you using?

trlx==0.5.0

### Additional system and package information

linux

**Comment by PhungVanDuy** [comment]
@jack-Dong please check this: https://github.com/CarperAI/trlx/issues/297#issuecomment-1441350580

**Comment by jack-Dong** [comment]
@PhungVanDuy Thank you for replying. I solve this problem by changing “get_prompt_dataset” function.
`def get_prompt_dataset(prompts, max_length):
        """
        Get the prompt after T5 decoding to make sure dictionary
        of prompts and summaries is consistent decode prompt from trlX pipeline
        """
        formatted_prompts = []
        for i in tqdm(range(len(prompts))):
            tmp = tokenizer.decode(
                tokenizer(
                    prompts[i].split("TL;DR:")[0],
                    truncation=True,
                    max_length=max_length - 5,  # to make sure "TL;DR" dont get truncated
                    add_special_tokens=False,
                )["input_ids"],
                skip_special_tokens=True,
            ).strip()
            tmp = tmp + "\nTL;DR:"
            
            #repeat decode encode utile don't change
            old_tmp = tmp
            while True:
                new_tmp = tokenizer.decode(
                    tokenizer(old_tmp, truncation=True, max_length=max_length, add_special_tokens=False)["input_ids"],
                    skip_special_tokens=True,
                ).strip()
                if new_tmp == old_tmp:
                    break
                else:
                    old_tmp = new_tmp
            formatted_prompts.append(old_tmp)
        return formatted_prompts`
I think your method may solve this issue too.
