### ISSUE TITLE
[deepspeed] OVERFLOW!

### ISSUE THREAD

**Issue by jack-Dong** [CarperAI/trlx#342]
### 🐛 Describe the bug

```
[losses/total_loss: 1.64 | losses/policy_loss: 0.12 | losses/value_loss: 7.62]:  16%|█████████████████                                                                                          | 1024/6400 [1:14:23<1:13:02,  1.23it/s][RANK 0] Collecting rollouts
[rollout 128 / 128]: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 128/128 [01:31<00:00,  1.40it/s][losses/total_loss: 1.34 | losses/policy_loss: -0.39 | losses/value_loss: 8.65]:  16%|█████████████████▎                                                                                        | 1044/6400 [1:16:09<1:07:04,  1.33it/s][2023-02-28 20:08:24,113] [INFO] [stage_1_and_2.py:1769:step] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 128.0, reducing to 64.0
[losses/total_loss: 4.35 | losses/policy_loss: -0.03 | losses/value_loss: 21.92]:  16%|█████████████████▍                                                                                         | 1045/6400 [1:16:09<53:12,  1.68it/s][2023-02-28 20:08:24,338] [INFO] [stage_1_and_2.py:1769:step] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 64.0, reducing to 32.0
[losses/total_loss: 4.35 | losses/policy_loss: -0.03 | losses/value_loss: 21.92]:  16%|█████████████████▍                                                                                         | 1046/6400 [1:16:10<43:15,  2.06it/s][2023-02-28 20:08:24,564] [INFO] [stage_1_and_2.py:1769:step] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 32.0, reducing to 16.0
[losses/total_loss: 4.35 | losses/policy_loss: -0.03 | losses/value_loss: 21.92]:  16%|█████████████████▌                                                                                         | 1047/6400 [1:16:10<36:19,  2.46it/s][2023-02-28 20:08:24,789] [INFO] [stage_1_and_2.py:1769:step] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 16.0, reducing to 8.0
[losses/total_loss: 4.35 | losses/policy_loss: -0.03 | losses/value_loss: 21.92]:  16%|█████████████████▌                                                                                         | 1048/6400 [1:16:10<31:26,  2.84it/s][2023-02-28 20:08:25,019] [INFO] [stage_1_and_2.py:1769:step] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 8.0, reducing to 4.0
[losses/total_loss: 4.53 | losses/policy_loss: -0.07 | losses/value_loss: 23.02]:  16%|█████████████████▌                                                                                         | 1049/6400 [1:16:10<28:08,  3.17it/s][2023-02-28 20:08:25,249] [INFO] [stage_1_and_2.py:1769:step] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 4.0, reducing to 2.0
[losses/total_loss: 4.53 | losses/policy_loss: -0.07 | losses/value_loss: 23.02]:  16%|█████████████████▌                                                                                         | 1050/6400 [1:16:11<25:51,  3.45it/s][2023-02-28 20:08:25,477] [INFO] [stage_1_and_2.py:1769:step] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 2.0, reducing to 1.0
[losses/total_loss: 4.53 | losses/policy_loss: -0.07 | losses/value_loss: 23.02]:  16%|█████████████████▌                                                                                         | 1051/6400 [1:16:11<24:11,  3.68it/s][2023-02-28 20:08:25,705] [INFO] [stage_1_and_2.py:1769:step] **[deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 1.0, reducing to 0.5**
[losses/total_loss: 1.73 | losses/policy_loss: -0.04 | losses/value_loss: 8.86]:  16%|█████████████████▊                                                                                          | 1056/6400 [1:16:14<54:09,  1.64it/s]Traceback (most recent call last):
  File "trlx_gptj_text_summarization.py", line 140, in <module>
    trainer = trlx.train(
  File "/cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/trlx/trlx.py", line 117, in train
    trainer.learn()
  File "/cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/trlx/trainer/accelerate_base_trainer.py", line 481, in learn
    self.accelerator.backward(loss)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1435, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/deepspeed.py", line 177, in backward
    self.engine.step()
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 2172, in step
    self._take_model_step(lr_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 2074, in _take_model_step
    self.optimizer.step()
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1766, in step
    self._update_scale(self.overflow)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 2023, in _update_scale
    self.loss_scaler.update_scale(has_overflow)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/fp16/loss_scaler.py", line 156, in update_scale
    raise Exception(
Exception: Current loss scale already at minimum - cannot decrease scale anymore. Exiting run.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/examples/summarize_rlhf/trlx_gptj_text_summari │
│ zation.py:140 in <module>                                                                        │
│                                                                                                  │
│   137 │   for i in range(len(val_prompts)):                                                      │
│   138 │   │   post_summary_dict[val_prompts[i]] = val_summaries[i]                               │
│   139 │                                                                                          │
│ ❱ 140 │   trainer = trlx.train(                                                                  │
│   141 │   │   reward_fn=reward_fn,                                                               │
│   142 │   │   prompts=train_prompts,                                                             │
│   143 │   │   eval_prompts=val_prompts[0:1000],  # sampling 1000 validation prompts for evalua   │
│                                                                                                  │
│ /cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/trlx/trlx.py:117 in train                      │
│                                                                                                  │
│   114 │   eval_pipeline = get_pipeline(config.train.pipeline)(eval_prompts, max_prompt_length,   │
│   115 │   trainer.add_eval_pipeline(eval_pipeline)                                               │
│   116 │                                                                                          │
│ ❱ 117 │   trainer.learn()                                                                        │
│   118 │   return trainer                                                                         │
│   119                                                                                            │
│                                                                                                  │
│ /cloudgpfs/workspace/dongshizhou/py_porjetcs/trlx/trlx/trainer/accelerate_base_trainer.py:481 in │
│ learn                                                                                            │
│                                                                                                  │
│   478 │   │   │   │   │   loss, stats = self.loss(batch)                                         │
│   479 │   │   │   │   │   forward_time = time() - forward_time                                   │
│   480 │   │   │   │   │   backward_time = time()                                                 │
│ ❱ 481 │   │   │   │   │   self.accelerator.backward(loss)                                        │
│   482 │   │   │   │   │   backward_time = time() - backward_time                                 │
│   483 │   │   │   │   │                                                                          │
│   484 │   │   │   │   │   self.opt.step()                                                        │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py:1435 in backward                │
│                                                                                                  │
│   1432 │   │   │   # deepspeed handles loss scaling by gradient_accumulation_steps in its `back  │
│   1433 │   │   │   loss = loss / self.gradient_accumulation_steps                                │
│   1434 │   │   if self.distributed_type == DistributedType.DEEPSPEED:                            │
│ ❱ 1435 │   │   │   self.deepspeed_engine_wrapped.backward(loss, **kwargs)                        │
│   1436 │   │   elif self.distributed_type == DistributedType.MEGATRON_LM:                        │
│   1437 │   │   │   return                                                                        │
│   1438 │   │   elif self.scaler is not None:                                                     │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/accelerate/utils/deepspeed.py:177 in backward             │
│                                                                                                  │
│   174 │   │   # - zero grad                                                                      │
│   175 │   │   # - checking overflow                                                              │
│   176 │   │   # - lr_scheduler step (only if engine.lr_scheduler is not None)                    │
│ ❱ 177 │   │   self.engine.step()                                                                 │
│   178 │   │   # and this plugin overrides the above calls with no-ops when Accelerate runs und   │
│   179 │   │   # Deepspeed, but allows normal functionality for non-Deepspeed cases thus enabli   │
│   180 │   │   # training loop that works transparently under many training regimes.              │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py:2172 in step                  │
│                                                                                                  │
│   2169 │   │   │   │   │   and self.quantizer.any_precision_switch()):                           │
│   2170 │   │   │   │   self._take_model_step(lr_kwargs, self.block_eigenvalue)                   │
│   2171 │   │   │   else:                                                                         │
│ ❱ 2172 │   │   │   │   self._take_model_step(lr_kwargs)                                          │
│   2173 │   │   │                                                                                 │
│   2174 │   │   │   report_progress = self.global_rank == 0 if self.global_rank else True         │
│   2175                                                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py:2074 in _take_model_step      │
│                                                                                                  │
│   2071 │   │   │   │   clip_grad_norm_(parameters=master_params,                                 │
│   2072 │   │   │   │   │   │   │   │   max_norm=self.gradient_clipping(),                        │
│   2073 │   │   │   │   │   │   │   │   mpu=self.mpu)                                             │
│ ❱ 2074 │   │   self.optimizer.step()                                                             │
│   2075 │   │                                                                                     │
│   2076 │   │   if hasattr(self.optimizer, '_global_grad_norm'):                                  │
│   2077 │   │   │   self._global_grad_norm = self.optimizer._global_grad_norm                     │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py:1766 in step      │
│                                                                                                  │
│   1763 │   │   timer_names = [OPTIMIZER_ALLGATHER, OPTIMIZER_GRADIENTS, OPTIMIZER_STEP]          │
│   1764 │   │                                                                                     │
│   1765 │   │   prev_scale = self.loss_scale                                                      │
│ ❱ 1766 │   │   self._update_scale(self.overflow)                                                 │
│   1767 │   │   if self.overflow:                                                                 │
│   1768 │   │   │   if dist.get_rank() == 0:                                                      │
│   1769 │   │   │   │   logger.info(                                                              ��
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py:2023 in           │
│ _update_scale                                                                                    │
│                                                                                                  │
│   2020 │   │   self._check_overflow(partition_gradients)                                         │
│   2021 │                                                                                         │
│   2022 │   def _update_scale(self, has_overflow=False):                                          │
│ ❱ 2023 │   │   self.loss_scaler.update_scale(has_overflow)                                       │
│   2024 │                                                                                         │
│   2025 │   # Promote state so it can be retrieved or set via "fp16_optimizer_instance.state"     │
│   2026 │   def _get_state(self):                                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deepspeed/runtime/fp16/loss_scaler.py:156 in update_scale │
│                                                                                                  │
│   153 │   │   │   # self.cur_scale /= self.scale_factor                                          │
│   154 │   │   │   if self.delayed_shift == 1 or self.cur_hysteresis == 1:                        │
│   155 │   │   │   │   if (self.cur_scale == self.min_scale) and self.raise_error_at_min_scale:   │
│ ❱ 156 │   │   │   │   │   raise Exception(                                                       │
│   157 │   │   │   │   │   │   "Current loss scale already at minimum - cannot decrease scale a   │
│   158 │   │   │   │   │   )                                                                      │
│   159 │   │   │   │   self.cur_scale = max(self.cur_scale / self.scale_factor, self.min_scale)   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
**Exception: Current loss scale already at minimum - cannot decrease scale anymore. Exiting run.**
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
```

deepspeed config
```
{
  "train_micro_batch_size_per_gpu": 2,
  "gradient_accumulation_steps": 4,
  "fp16": {
    "enabled": true,
    "min_loss_scale": 0.5,
    "fp16_scale_tolerance": 0.25,
    "opt_level": "O2"
  },
  "zero_optimization": {
    "stage": 2,
    "offload_param": {
      "device": "cpu"
    },
    "offload_optimizer": {
      "device": "cpu"
    },
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "contiguous_gradients": true
  }
}

```

### Which trlX version are you using?

trlx==0.5.0,deepspeed==0.8.1,transformers==4.21.2

### Additional system and package information

linux

**Comment by PhungVanDuy** [comment]
@jack-Dong  can you share your wandb?

**Comment by jack-Dong** [comment]
@PhungVanDuy 
[https://wandb.ai/shizhoudong/trlx/runs/9arnysxj?workspace=user-shizhoudong](wandb)

**Comment by PhungVanDuy** [comment]
> @PhungVanDuy [https://wandb.ai/shizhoudong/trlx/runs/9arnysxj?workspace=user-shizhoudong](wandb)

Just a quick read I saw to train the GPT-2 model PPO instead of GPT-J, with the GPT-2 model much smaller than GPT-J, I suggest that you can try to train with fp32.

**Comment by jack-Dong** [comment]
@PhungVanDuy  Very thank you for replaying， But if I train a larger model like GPT-J， how can I solve this problem？

**Comment by PhungVanDuy** [comment]
> @PhungVanDuy Very thank you for replaying， But if I train a larger model like GPT-J， how can I solve this problem？

Actually, it is hard to say, because training GPT-J with fp32 is pretty hard. There have several things that we can try when facing this error: (setting `--fp16-scale-tolerance=0.25`, reducing `min-loss-scale`, reducing learning rate, switching fp32). But with my experience with this summarization, it does not get that problem with GPT-J.

**Comment by jack-Dong** [comment]
> > @PhungVanDuy Very thank you for replaying， But if I train a larger model like GPT-J， how can I solve this problem？
> 
> Actually, it is hard to say, because training GPT-J with fp32 is pretty hard. There have several things that we can try when facing this error: (setting `--fp16-scale-tolerance=0.25`, reducing `min-loss-scale`, reducing learning rate, switching fp32). But with my experience with this summarization, it does not get that problem with GPT-J.

OK， I will try these suggestions which you provided， thank you for your time.

**Comment by DayoungKwon** [comment]
I faced the same issue. How did you resolve? 
I tried to reduce min-loss-scale, i've still got an error.
