### ISSUE TITLE
Deepspeed batch_size 32 vs hf batch_size  4

### ISSUE THREAD

**Issue by joan126** [CarperAI/trlx#376]
### 🐛 Describe the bug

when python run examples/summarize_rlhf/reward_model/train_reward_model_gptj.py

an error occurs as below:

`Traceback (most recent call last):
  File "train_reward_model_gptj.py", line 140, in <module>
    Trainer(
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1633, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1702, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/opt/conda/lib/python3.8/site-packages/transformers/deepspeed.py", line 346, in deepspeed_init
    hf_deepspeed_config.trainer_config_finalize(args, model, num_training_steps)
  File "/opt/conda/lib/python3.8/site-packages/transformers/deepspeed.py", line 221, in trainer_config_finalize
    raise ValueError(
ValueError: Please correct the following DeepSpeed config values that mismatch TrainingArguments values:
- ds train_batch_size=32 vs hf train_batch_size (calculated)=4
The easiest method is to set these DeepSpeed config values to 'auto'.`

### Which trlX version are you using?

trlX codes from master branch

### Additional system and package information

python 3.8.12  transformers 4.27.1 deepspeed 0.7.7

**Comment by PhungVanDuy** [comment]
I guess you trained on 4 GPUs and with the current config in `train_reward_model_gptj.py` I think you have to change this [line]( (https://github.com/CarperAI/trlx/blob/main/examples/summarize_rlhf/reward_model/ds_config_gpt_j.json#L2) to 4. An easier way is to set that value to `auto`.
