### ISSUE TITLE
DDP and hydra model

### ISSUE THREAD

**Issue by reciprocated** [CarperAI/trlx#51]
### 🐛 Describe the bug

Hydra model doesn't play nicely with ddp

```Traceback (most recent call last):
  File "examples/ppo_sentiments.py", line 18, in <module>
    model = trlx.train(
  File "/trlx/trlx/trlx.py", line 92, in train
    model.learn()
  File "/trlx/trlx/model/accelerate_base_model.py", line 209, in learn
    loss, stats = self.loss(batch)
  File "/trlx/trlx/model/accelerate_ppo_model.py", line 112, in loss
    logits, _, vpred = self.model(
  File "/trlx/.env/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/trlx/.env/lib64/python3.8/site-packages/torch/nn/parallel/distributed.py", line 994, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by
passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the
return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 31 32 33
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
```

```
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
use_cpu: false
```

```accelerate launch --num_processes 2 --num_machines 1 --config_file ddp.yaml examples/ppo_sentiments.py```

This is a relevant discussion
https://github.com/pytorch/pytorch/issues/43259

### Which trlX version are you using?

stage-api @ 8057d16

**Comment by LouisCastricato** [comment]
@Dahoas

**Comment by Dahoas** [comment]
Hmm I'll look into it. I've only been testing with deepspeed. Is there ever a reason we would want to use ddp vs deepspeed?

**Comment by LouisCastricato** [comment]
I'm not sure there's a need for DDP

**Comment by LouisCastricato** [comment]
I would say lets close this issue. I don't think DDP is worth the effort.

**Comment by Dahoas** [comment]
Let's just make clear we only support deepspeed.

**Comment by LouisCastricato** [comment]
Ok so I think the solution is to update the readme/docs and leave it at that. Lets close this issue.
