### ISSUE TITLE
TypeError: reward_fn() got an unexpected keyword argument 'tokenizer'

### ISSUE THREAD

**Issue by sayan1101** [CarperAI/trlx#569]
### 🐛 Describe the bug

cloned the repo and ran t5_summarize_daily_cnn.py that is present in trlx/examples/summarize_daily_cnn. got the following error:

'''
Traceback (most recent call last):
  File "/workspace/trlx/examples/summarize_daily_cnn/t5_summarize_daily_cnn.py", line 137, in <module>
    trlx.train(
  File "/workspace/trlx/trlx/trlx.py", line 129, in train
    trainer.learn()
  File "/workspace/trlx/trlx/trainer/accelerate_base_trainer.py", line 521, in learn
    self.prepare_learning()
  File "/workspace/trlx/trlx/trainer/accelerate_ppo_trainer.py", line 235, in prepare_learning
    self.make_experience(self.config.method.num_rollouts)
  File "/workspace/trlx/trlx/trainer/accelerate_ppo_trainer.py", line 310, in make_experience
    all_scores = self.reward_fn(
TypeError: reward_fn() got an unexpected keyword argument 'tokenizer'
Traceback (most recent call last):
  File "/workspace/trlx/examples/summarize_daily_cnn/t5_summarize_daily_cnn.py", line 137, in <module>
    trlx.train(
  File "/workspace/trlx/trlx/trlx.py", line 129, in train
    trainer.learn()
  File "/workspace/trlx/trlx/trainer/accelerate_base_trainer.py", line 521, in learn
    self.prepare_learning()
  File "/workspace/trlx/trlx/trainer/accelerate_ppo_trainer.py", line 235, in prepare_learning
    self.make_experience(self.config.method.num_rollouts)
  File "/workspace/trlx/trlx/trainer/accelerate_ppo_trainer.py", line 310, in make_experience
    all_scores = self.reward_fn(
TypeError: reward_fn() got an unexpected keyword argument 'tokenizer'
'''

**Comment by maxreciprocate** [comment]
Hello @sayan1101! This should be fix with #570, thanks for spotting this!
